services:
  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    restart: always
    logging:
      options:
        max-size: "500M"
    volumes:
      - ./config/kavita:/config
      - ${STORAGE_DIR}:${STORAGE_DIR}
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    labels:
      - autoheal=true
      - "traefik.enable=true"
      - "traefik.http.routers.kavita.rule=Host(`kavita.${DOMAIN}`)"
      - "traefik.http.routers.kavita.tls=true"
    # ports:
    # - "5000:5000"
    healthcheck:
      test: "curl -ILXGET http://localhost:5000"

networks:
  default:
    external: true
    name: traefik
