services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: "sonarr"
    restart: always
    volumes:
      - ./config:/config
      - ${STORAGE_DIR}:${STORAGE_DIR}
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    labels:
      - "autoheal=true"
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.priority=1"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.${DOMAIN}`)"
      - "traefik.http.routers.sonarr.tls=true"
      - "traefik.http.routers.sonarr.middlewares=authentik@file"
      - "traefik.http.routers.sonarr-api.priority=2"
      - "traefik.http.routers.sonarr-api.rule=Host(`sonarr.${DOMAIN}`) && PathPrefix(`/api/`)"
      - "traefik.http.routers.sonarr-api.tls=true"
    healthcheck:
      test: "curl -ILXGET http://localhost:8989"

networks:
  default:
    external: true
    name: traefik
