version: "3.7"

services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: "sonarr"
    restart: unless-stopped
    volumes:
      - ./config:/config
      - ${STORAGE_DIR}:${STORAGE_DIR}
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    labels:
      - "autoheal=true"
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.${DOMAIN}`)"
      - "traefik.http.routers.sonarr.tls.certresolver=myresolver"
    healthcheck:
      test: "curl -ILXGET http://localhost:8989"

networks:
  default:
    external:
      name: traefik
