version: "3.7"

services:
  transmission:
    image: linuxserver/transmission
    volumes:
      - ${CONFIG_DIR}/transmission:/config
      - ${STORAGE_DIR}:/storage
    environment:
      - TZ=Australia/Brisbane
      - PUID=${PUID}
      - PGID=${PGID}
    healthcheck:
      test: "curl -ILXGET http://localhost:9091"
    labels:
      - traefik.enable=true
      - traefik.port=9091
      - traefik.frontend.rule=Host:transmission.${DOMAIN}

  sonarr:
    image: linuxserver/sonarr
    environment:
      - "PGID=${PGID}"
      - "PUID=${PUID}"
    depends_on:
      - jackett
    volumes:
      - $CONFIG_DIR/sonarr:/config:rw
      - ${STORAGE_DIR}:${STORAGE_DIR}:rw
    healthcheck:
      test: "curl -ILXGET http://localhost:8989"
    labels:
      - traefik.enable=true
      - traefik.port=8989
      - traefik.frontend.rule=Host:sonarr.${DOMAIN}

  radarr:
    image: linuxserver/radarr
    environment:
      - "PGID=${PGID}"
      - "PUID=${PUID}"
    depends_on:
      - jackett
    volumes:
      - $CONFIG_DIR/radarr:/config
      - ${STORAGE_DIR}:${STORAGE_DIR}:rw
    healthcheck:
      test: "curl -ILXGET http://localhost:7878"
    labels:
      - traefik.enable=true
      - traefik.port=7878
      - traefik.frontend.rule=Host:radarr.${DOMAIN}

  jackett:
    image: linuxserver/jackett
    environment:
      - "PGID=${PGID}"
      - "PUID=${PUID}"
    volumes:
      - $CONFIG_DIR/jackett:/config
    healthcheck:
      test: "curl -ILXGET http://localhost:9117"
    labels:
      - traefik.enable=true
      - traefik.port=9117
      - traefik.frontend.rule=Host:jackett.${DOMAIN}

networks:
  default:
    external:
      name: traefik
