version: "3.7"

services:
  vpn:
    image: dperson/openvpn-client
    restart: unless-stopped
    volumes:
      - ./vpn:/vpn
    devices:
      - /dev/net/tun
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    ports:
      - "9091:9091"
      - "8989:8989"
      - "7878:7878"
      - "9117:9117"
    labels:
      - autoheal=true
    command: "-f ''"

  transmission:
    image: linuxserver/transmission
    network_mode: "service:vpn"
    volumes:
      - ${CONFIG_DIR}/transmission:/config
      - ${STORAGE_DIR}:/storage
    environment:
      - TZ=Australia/Brisbane
      - PUID=${PUID}
      - PGID=${PGID}
    labels:
      - autoheal=true
    healthcheck:
      test: "curl -ILXGET http://localhost:9091"

  sonarr:
    image: linuxserver/sonarr
    network_mode: "service:vpn"
    environment:
      - "PGID=${PGID}"
      - "PUID=${PUID}"
    labels:
      - autoheal=true
    depends_on:
      - jackett
    volumes:
      - $CONFIG_DIR/sonarr:/config:rw
      - ${STORAGE_DIR}:${STORAGE_DIR}:rw
    healthcheck:
      test: "curl -ILXGET http://localhost:8989"

  radarr:
    image: linuxserver/radarr
    network_mode: "service:vpn"
    environment:
      - "PGID=${PGID}"
      - "PUID=${PUID}"
    labels:
      - autoheal=true
    depends_on:
      - jackett
    volumes:
      - $CONFIG_DIR/radarr:/config
      - ${STORAGE_DIR}:${STORAGE_DIR}:rw
    healthcheck:
      test: "curl -ILXGET http://localhost:7878"

  jackett:
    image: linuxserver/jackett
    network_mode: "service:vpn"
    environment:
      - "PGID=${PGID}"
      - "PUID=${PUID}"
    labels:
      - autoheal=true
    volumes:
      - $CONFIG_DIR/jackett:/config
    healthcheck:
      test: "curl -ILXGET http://localhost:9117"
