FROM nodered/node-red
RUN npm install node-red-contrib-home-assistant-websocket
RUN npm install node-red-contrib-time-range-switch
RUN npm install node-red-contrib-traffic
RUN npm install node-red-contrib-telegrambot
