services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    privileged: true
    ports:
      - 4000:4000 # Main service port
    environment:
      - ENCRYPTION_KEY=${TESLAMATE_ENCRYPTION_KEY}
      - DATABASE_USER=${TESLAMATE_DATABASE_USER}
      - DATABASE_PASS=${TESLAMATE_DATABASE_PASS}
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=teslamate-database
      - MQTT_HOST=mosquitto
      - TZ=${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.teslamate.rule=Host(`teslamate.${DOMAIN}`)"
      - "traefik.http.routers.teslamate.tls.certresolver=myresolver"
      - "traefik.http.routers.teslamate.middlewares=authentik@file"
    cap_drop:
      - all

  teslamate-database:
    image: postgres:17
    restart: always
    volumes:
      - ./config/database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${TESLAMATE_DATABASE_USER}
      - POSTGRES_PASSWORD=${TESLAMATE_DATABASE_PASS}
      - POSTGRES_DB=teslamate
    # ports:
    #   - 13306:3306

  teslamate-grafana:
    image: teslamate/grafana:latest
    restart: always
    volumes:
      - ./config/grafana:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DATABASE_USER=${TESLAMATE_DATABASE_USER}
      - DATABASE_PASS=${TESLAMATE_DATABASE_PASS}
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=teslamate-database
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.teslamate-grafana.rule=Host(`teslamate-grafana.${DOMAIN}`)"
      - "traefik.http.routers.teslamate-grafana.tls.certresolver=myresolver"
      
  mosquitto:
    image: eclipse-mosquitto:2
    restart: always
    command: mosquitto -c /mosquitto-no-auth.conf
    # ports:
    #   - 1883:1883
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

  backup:
    image: prodrigestivill/postgres-backup-local:14
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_HOST: teslamate-database
      POSTGRES_CLUSTER: "TRUE"
      POSTGRES_USER: ${TESLAMATE_DATABASE_USER}
      POSTGRES_PASSWORD: ${TESLAMATE_DATABASE_PASS}
      POSTGRES_DB: teslamate
      SCHEDULE: "@daily"
      POSTGRES_EXTRA_OPTS: "--clean --if-exists"
      BACKUP_DIR: /db_dumps
    volumes:
      - ${STORAGE_DIR}/backups/teslamate-database:/db_dumps
    depends_on:
      - teslamate-database

networks:
  default:
    external:
      name: traefik

volumes:
  mosquitto-conf:
  mosquitto-data:
