version: "3.7"

services:
  home-assistant:
    image: homeassistant/home-assistant
    volumes:
      - ${CONFIG_DIR}/hass:/config
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: "curl -ILXGET http://localhost:8123"
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.port=8123
        - traefik.frontend.rule=Host:hass.${DOMAIN}
  node-red:
    image: node-red-local:latest
    volumes:
      - ${CONFIG_DIR}/node-red:/data
    healthcheck:
      test: "curl -ILXGET http://localhost:1880"
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.port=1880
        - traefik.frontend.rule=Host:node-red.${DOMAIN}

networks:
  default:
    external:
      name: traefik
