version: "3.7"

services:
  home-assistant:
    image: homeassistant/home-assistant:2020.12.2
    restart: always
    network_mode: host # most things with auto-discovery such as homekit require this currently
    volumes:
      - ${CONFIG_DIR}/hass:/config
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: "curl -ILXGET http://localhost:8123"
    depends_on:
      - mqtt
      - home-assistant-database
    labels:
      - autoheal=true
  home-assistant-database:
    image: mysql:8
    volumes:
      - ${CONFIG_DIR}/hass-database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${HASS_MYSQL_PASSWORD}
    ports:
      - 13306:3306
    labels:
      - autoheal=true

  node-red:
    build: ./node-red
    restart: always
    volumes:
      - ${CONFIG_DIR}/node-red:/data
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: "curl -ILXGET http://localhost:1880"
    depends_on:
      - home-assistant
    labels:
      - traefik.enable=true
      - traefik.port=1880
      - traefik.frontend.rule=Host:node-red.${DOMAIN}
      - autoheal=true
  mqtt:
    image: eclipse-mosquitto
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ${CONFIG_DIR}/mosquitto:/mosquitto
    healthcheck:
      test: "nc -z localhost 1883"
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    restart: always
    labels:
      - autoheal=true
    volumes:
      - ${CONFIG_DIR}/zigbee2mqtt:/app/data
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    depends_on:
      - mqtt
networks:
  default:
    external:
      name: traefik
