version: "3.7"

services:
  home-assistant:
    image: homeassistant/home-assistant
    restart: always
    network_mode: host
    volumes:
      - ${CONFIG_DIR}/hass:/config
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: "curl -ILXGET http://localhost:8123"
  node-red:
    build: ./node-red
    restart: always
    ports:
      - "1880:1880"
    volumes:
      - ${CONFIG_DIR}/node-red:/data
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: "curl -ILXGET http://localhost:1880"
  mqtt:
    image: eclipse-mosquitto
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ${CONFIG_DIR}/mosquitto:/mosquitto
    healthcheck:
      test: "nc -z localhost 1883"
