version: "3.7"

services:
  home-assistant:
    image: homeassistant/home-assistant:0.97.2
    restart: always
    network_mode: host # hue bridge and xiaomi hub both require this currently
    volumes:
      - ${CONFIG_DIR}/hass:/config
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: "curl -ILXGET http://localhost:8123"
  node-red:
    build: ./node-red
    restart: always
    volumes:
      - ${CONFIG_DIR}/node-red:/data
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: "curl -ILXGET http://localhost:1880"
    labels:
      - traefik.enable=true
      - traefik.port=1880
      - traefik.frontend.rule=Host:node-red.${DOMAIN}
#  node-red-old:
#    build: ./node-red-old
#    restart: always
#    volumes:
#      - ${CONFIG_DIR}/node-red-old:/data
#      - /etc/localtime:/etc/localtime:ro
#    healthcheck:
#      test: "curl -ILXGET http://localhost:1880"
#    labels:
#      - traefik.enable=true
#      - traefik.port=1880
#      - traefik.frontend.rule=Host:node-red-old.${DOMAIN}
  mqtt:
    image: eclipse-mosquitto
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ${CONFIG_DIR}/mosquitto:/mosquitto
    healthcheck:
      test: "nc -z localhost 1883"

networks:
  default:
    external:
      name: traefik
