services:
  proxy:
    image: nginx
    restart: always
    network_mode: host
    logging:
      options:
        max-size: "500M"
    volumes:
      - ./config/certs:/certs
      - ./nginx.conf:/nginx.conf
    environment:
      - TZ=${TZ}
      - DOMAIN=${DOMAIN}
    labels:
      - autoheal=true
    command: /bin/bash -c "envsubst '$$DOMAIN' < /nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  certbot:
    image: certbot/dns-cloudflare
    volumes:
      - ./config/certs:/etc/letsencrypt
      - ./config/cloudflare.ini:/cloudflare.ini
    command: certonly --dns-cloudflare --dns-cloudflare-credentials /cloudflare.ini -d "*.${DOMAIN}" --agree-tos --non-interactive --email ${EMAIL}
  cron:
    build: cron
    entrypoint: /bin/sh -c "echo '0 0 * * * /usr/local/bin/docker-compose run certbot renew && /usr/local/bin/docker-compose exec proxy nginx -s reload' | crontab - && crond -f"
    working_dir: /app
    volumes:
      - .:/app
      - ./data:/var/www/certbot
