services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    restart: always
    network_mode: host
    volumes:
      - ./config:/config
      - ${STORAGE_DIR}:${STORAGE_DIR}
    devices:
      - /dev/dri:/dev/dri
    environment:
      - TZ=${TZ}
      - PGID=${PGID}
      - PUID=${PUID}
    labels:
      - autoheal=true
    healthcheck:
      test: "curl -IXGET http://localhost:32400/web"
      
