version: '3.9'
services:
  palworld-dedicated-server:
    build: .
    container_name: palworld-dedicated-server
    image: jammsen/palworld-dedicated-server:latest
    restart: always
    network_mode: bridge
    ports:
      - target: 8211 # gamerserver port inside of the container
        published: 8211 # gamerserver port on your host
        protocol: udp
        mode: host
      - target: 25575 # rcon port inside of the container
        published: 25575 # rcon port on your host
        protocol: tcp
        mode: host
    environment:
      - ALWAYS_UPDATE_ON_START=true
      - MAX_PLAYERS=32
      - MULTITHREAD_ENABLED=true
      - COMMUNITY_SERVER=false
      - RCON_ENABLED=true
      - RCON_PORT=25575
      - SERVER_NAME=justins-palworld-###RANDOM###
      - SERVER_DESCRIPTION=Justins-Palworld
      - "SERVER_PASSWORD=${PALWORLD_PASSWORD}"
      - "ADMIN_PASSWORD=${PALWORLD_ADMIN_PASSWORD}"
    volumes:
      - ./config:/palworld
  
  rcon:
    image: outdead/rcon:latest
    entrypoint: ['/rcon', '-a', 'localhost:25575', '-p', 'pokemon2']
    profiles: ['rcon'] 
    network_mode: host
