FROM nodered/node-red:3.0.2
RUN npm install node-red-contrib-home-assistant-websocket
RUN npm install node-red-contrib-time-range-switch
RUN npm install node-red-contrib-traffic
RUN npm install node-red-contrib-telegrambot
RUN npm install node-red-contrib-tesla@^2
