services:
  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd
    container_name: "sabnzbd"
    restart: always
    volumes:
      - ./config:/config
      - ${STORAGE_DIR}:${STORAGE_DIR}
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    labels:
      - "autoheal=true"
      - "traefik.enable=true"
      - "traefik.http.routers.sabnzbd.priority=1"
      - "traefik.http.routers.sabnzbd.rule=Host(`sabnzbd.${DOMAIN}`)"
      - "traefik.http.routers.sabnzbd.tls=true"
      - "traefik.http.routers.sabnzbd.middlewares=authentik@file"
      - "traefik.http.routers.sabnzbd-api.priority=2"
      - "traefik.http.routers.sabnzbd-api.rule=Host(`sabnzbd.${DOMAIN}`) && PathPrefix(`/sabnzbd/api/`)"
      - "traefik.http.routers.sabnzbd-api.tls=true"
    healthcheck:
      test: "curl -ILXGET http://localhost:8080"

networks:
  default:
    external: true
    name: traefik
