version: "3.3"

services:

  traefik:
    image: "traefik:v2.6"
    restart: unless-stopped
    container_name: "traefik"
    networks:
      - traefik
    command:
      - "--certificatesresolvers.myresolver.acme.email=${EMAIL}"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./config/letsencrypt:/letsencrypt"
      - "./config/traefik.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

# Example container
  # whoami:
  #   image: "traefik/whoami"
  #   networks:
  #     - traefik
  #   container_name: "simple-service"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.whoami.rule=Host(`whoami.dray.id.au`)"
  #     #- "traefik.http.routers.whoami.entrypoints=websecure" # This is optional
  #     - "traefik.http.routers.whoami.tls.certresolver=myresolver"

networks:
  traefik:
    name: traefik
    attachable: true
