version: "3.7"

services:
  traefik:
    image: traefik:alpine
    networks:
      - traefik
    command:
      - "--acme.email=${EMAIL}"
    ports:
      - "80:80"
      - "443:443"
      - "8081:8081"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ${CONFIG_DIR}/traefik/acme:/acme

networks:
  traefik:
    name: traefik
    attachable: true
