version: "3.7"

services:
  traefik:
    image: traefik:alpine
    networks:
      - traefik
    command:
      - "--acme.domains=*.${DOMAIN}"
      - "--acme.email=${EMAIL}"
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_API}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ${CONFIG_DIR}/traefik/acme:/acme
    deploy:
      replicas: 1
      placement:
        constraints: [node.role==manager]

networks:
  traefik:
    name: traefik
    attachable: true
