http:
  routers:
    service-home-assistant:
      rule: "Host(`home-assistant.dray.id.au`)"
      service: "service-home-assistant"
      tls:
        certresolver: "myresolver"

  services:
    service-home-assistant:
      loadBalancer:
        servers:
          - url: "http://192.168.4.20:8123"
