http:
  routers:
    dashboard:
      rule: Host(`traefik.dray.id.au`)
      service: api@internal
      middlewares:
        - authentik@docker
      tls:
        certresolver: myresolver

    service-home-assistant:
      rule: "Host(`home-assistant.dray.id.au`)"
      service: "service-home-assistant"
      tls:
        certresolver: "myresolver"

  services:
    service-home-assistant:
      loadBalancer:
        servers:
          - url: "http://192.168.4.20:8123"
