################################################################
# Global configuration
################################################################

# Log level
#
# Optional
# Default: "ERROR"
#
[log]
level = "DEBUG"

[accessLog]

################################################################
# Entrypoints configuration
################################################################

# Entrypoints definition
#
# Optional
# Default:
[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.web.http]
    [entryPoints.web.http.redirections]
      [entryPoints.web.http.redirections.entryPoint]
        to = "websecure"
        scheme = "https"

[entryPoints.websecure]
  address = ":443"

[certificatesresolvers.myresolver.acme]
  tlschallenge = true
  caserver = "https://acme-staging-v02.api.letsencrypt.org/directory"
#  email = "justin@dray.id.au"
  storage = "/letsencrypt/acme.json"

################################################################
# API and dashboard configuration
################################################################

# Enable API and dashboard
[api]
  insecure = true

################################################################
# Docker configuration backend
################################################################

# Enable Docker configuration backend
#[providers.docker]
#  exposedbydefault = false


################################################################
# Static endpoints
################################################################

[providers.file]
    filename = "/etc/traefik/traefik-dynamic.yaml"
