#!/bin/bash
dir="$(dirname "$(readlink -f "$0")")"
name="$(basename "$dir")"
cd "$dir"
image_list="$(cat docker-stack.yml|grep -E '^\s+image:' | awk '{print $2}')"

if [[ $1 != '--fast' ]]; then
	echo "Pulling latest images..."
	for image in $image_list; do
		docker pull $image
	done
fi

source "$dir/grafana.conf"

# Generate initial influxdb config if it doesn't exist
mkdir -p "$INFLUX_STORAGE" "$GRAFANA_STORAGE"
INFLUX_IMAGE="$(grep -o "influxdb:[0-9].*" "$dir/docker-stack.yml")"
INFLUX_CONFIG="$INFLUX_STORAGE/influxdb.conf"
[[ ! -e $INFLUX_CONFIG ]] && docker run --rm $INFLUX_IMAGE influxd config > $INFLUX_CONFIG

echo "Installing/updating stack..."
source grafana.conf
docker stack deploy --compose-file docker-stack.yml grafana
