services:
  home-assistant:
    image: homeassistant/home-assistant:2024.7
    restart: unless-stopped
    privileged: true
    volumes:
      - ./config/home-assistant:/config
      - ${STORAGE_DIR}:${STORAGE_DIR}
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 8123:8123 # Main service port
      - 21063:21063 # Homekit bridge
    labels:
      - "autoheal=true"
      - "traefik.enable=true"
      - "traefik.http.routers.home-assistant.priority=1"
      - "traefik.http.routers.home-assistant.rule=Host(`home-assistant.${DOMAIN}`)"
      - "traefik.http.routers.home-assistant.tls.certresolver=myresolver"
      - "traefik.http.routers.home-assistant.middlewares=authentik@file"
      - "traefik.http.routers.home-assistant-api.priority=2"
      - "traefik.http.routers.home-assistant-api.rule=Host(`home-assistant.${DOMAIN}`) && PathPrefix(`/api/`)"
      - "traefik.http.routers.home-assistant-api.tls.certresolver=myresolver"
      # No-authentik endpoint (Allows login directly without the auth redirect)
      # - "traefik.http.middlewares.home-assistant-na.headers.customrequestheaders.X-authentik-username=" # Remove auth'd username header to prevent bypass
      # - "traefik.http.routers.home-assistant-na.rule=Host(`home-assistant-na.${DOMAIN}`)"
      # - "traefik.http.routers.home-assistant-na.tls.certresolver=myresolver"
    healthcheck:
      test: "curl -ILXGET http://localhost:8123"

  home-assistant-database:
    image: mysql:8
    restart: unless-stopped
    # labels:
    #   - autoheal=true
    volumes:
      - ./config/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${HASS_MYSQL_PASSWORD}
    # ports:
    #   - 13306:3306

  sungather:
    image: bohdans/sungather
    restart: unless-stopped
    logging:
      options:
        max-size: "500M"
    volumes:
      - ./config/sungather/config.yaml:/config/config.yaml
      - ${STORAGE_DIR}:${STORAGE_DIR}
    environment:
      - TZ=${TZ}
    labels:
      - autoheal=true

  mqtt:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    labels:
      - autoheal=true
    ports:
      - 1883:1883
    volumes:
      - ./config/mosquitto:/mosquitto
    environment:
      - MQTT_TEST_USER_NAME=$MQTT_TEST_USER_NAME
      - MQTT_TEST_USER_PASSWORD=$MQTT_TEST_USER_PASSWORD
    healthcheck:
      test: "mosquitto_pub -u $MQTT_TEST_USER_NAME -P $MQTT_TEST_USER_PASSWORD -t test_topic -m test-message"

  zigbee2mqtt:
    build: ./zigbee2mqtt
    restart: always
    ports:
      - 8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zigbee2mqtt.rule=Host(`zigbee2mqtt.${DOMAIN}`)"
      - "traefik.http.routers.zigbee2mqtt.tls.certresolver=myresolver"
      - "traefik.http.routers.zigbee2mqtt.middlewares=authentik@file"
      - "autoheal=true"
    environment:
      - TZ=${TZ}
    volumes:
      - ./config/zigbee2mqtt:/app/data
      - ./config/shared:/shared
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    depends_on:
      - mqtt
#    healthcheck:
#      test: "/bin/grep -q ok /shared/reset-zigbee" # Reset when the message is anything other than "ok"

networks:
  default:
    external:
      name: traefik
