version: "3.7"

services:
  jackett:
    image: linuxserver/jackett
    volumes:
      - ./config:/config
    environment:
      - TZ=${TZ}
      - PGID=${PGID}
      - PUID=${PUID}
    labels:
      - autoheal=true
      - "traefik.enable=true"
      - "traefik.http.routers.jackett.rule=Host(`jackett.${DOMAIN}`)"
      - "traefik.http.routers.jackett.tls.certresolver=myresolver"
    healthcheck:
      test: "curl -IXGET http://localhost:9117"

networks:
  default:
    external:
      name: traefik