version: "3.7"

services:
  chia:
    build: chia
    restart: unless-stopped
    healthcheck:
      test: "echo"
    ports:
        - 8444:8444
        - 8555:8555
    volumes:
        - ${CONFIG_DIR}/chia:/root/.chia

