version: "3.7"

services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    restart: unless-stopped
    volumes:
      - ./config:/config
      - ${STORAGE_DIR}:${STORAGE_DIR}
    devices:
      - /dev/dri:/dev/dri
    environment:
      - TZ=${TZ}
      - PGID=${PGID}
      - PUID=${PUID}
      - JELLYFIN_PublishedServerUrl=192.168.4.20 # Used for autodiscovery only
    labels:
      - autoheal=true
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAIN}`)"
      - "traefik.http.routers.jellyfin.tls.certresolver=myresolver"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
    ports:
      - 8096:8096 # WebUI
      - 7359:7359/udp # Local Discovery
      # - 1900:1900/udp # DNLA Discovery
    healthcheck:
      test: "curl -ILXGET http://localhost:8096/web"

networks:
  default:
    external:
      name: traefik
