services:
  komga:
    image: gotson/komga
    container_name: "komga"
    restart: unless-stopped
    volumes:
      - ./config:/config
      - ${STORAGE_DIR}:${STORAGE_DIR}
    user: ${PUID}:${PGID}
    labels:
      - "autoheal=true"
      - "traefik.enable=true"
      - "traefik.http.routers.manga.rule=Host(`manga.${DOMAIN}`)"
      - "traefik.http.routers.manga.tls.certresolver=myresolver"
#    healthcheck: # curl was removed from the latest image in 2024
#      test: "curl -ILXGET http://localhost:25600"

networks:
  default:
    external:
      name: traefik
