version: "3.7"

services:
  netdata:
    image: netdata/netdata
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor=unconfined
    healthcheck:
      test: "curl -ILX GET localhost:19999"
    ports:
      - "19999:19999"
    volumes:
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./netdata.conf:/etc/netdata/netdata.conf:ro"
