version: "3.7"

services:
  unifi-controller:
    image: linuxserver/unifi-controller
    network_mode: host
    container_name: unifi-controller
    volumes:
      - ${CONFIG_DIR}/unifi-controller:/config
#    ports:
#      - 3478:3478/udp # Unifi communication port
#      - 10001:10001/udp # AP Discovery
#      - 8080:8080 # required for Unifi to function
#      - 8081:8081 # Unifi communication port
#      - 8443:8443 # Unifi communication port
#      - 8843:8843 # Unifi communication port
#      - 8880:8880 # Unifi communication port
#      - 6789:6789 # For throughput test
    restart: unless-stopped
