version: "3.7"

services:
  syncthing:
    image: ghcr.io/linuxserver/syncthing
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${CONFIG_DIR}/syncthing:/config
      - /home/downloads/Dropbox:/Dropbox
      - ${STORAGE_DIR}/syncthing:/syncthing
    healthcheck:
      test: "apk add -U curl && curl -s localhost:8384|grep 'Not Authorized'"
    labels:
      - autoheal=true
    network_mode: host
    restart: unless-stopped
