version: "3.7"

services:
  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    restart: unless-stopped
    volumes:
      - ./config:/config
      - ${STORAGE_DIR}:${STORAGE_DIR}
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - USER=${MEDIA_USER}
      - PASS=${MEDIA_PASSWORD}
    labels:
      - autoheal=true
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.rule=Host(`transmission.${DOMAIN}`)"
      - "traefik.http.routers.transmission.tls.certresolver=myresolver"
    ports:
      - "13100:13100"
    healthcheck:
      test: "curl -ILXGET http://localhost:9091"

networks:
  default:
    external:
      name: traefik
