version: "3.7"

services:
  valheim:
    #image: lloesche/valheim-server
    image: mbround18/valheim:latest
    restart: unless-stopped
    environment:
      - PORT=2456
      - NAME=Justins-Server-1234
      - WORLD=asdfasdf
      - PASSWORD="${VALHEIM_SERVER_PASSWORD}"
      - TZ=Australia/Brisbane
      - PUBLIC=1
    ports:
        - 2456:2456/udp
        - 2457:2457/udp
        - 2458:2458/udp
    volumes:
        - ${CONFIG_DIR}/games/valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
        - ${CONFIG_DIR}/games/valheim/server:/home/steam/valheim

